import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-w-screen`}
      >
        <header className="w-full fixed top-0 left-0 right-0 z-50">
          <Navbar />
        </header>
        <div className="flex pt-[93px] min-w-full">
          <Sidebar />
          <main className="flex-1 pl-8 pt-5">{children}</main>
        </div>
      </body>
    </html>
  );
}
